name: "🐛 Fix"
description: "Fix Template"
title: "[fix] "
labels:
  - "fix"

body:
  - type: input
    id: description
    attributes:
      label: "🐛 버그 내용(Description)"
      description: "고칠 버그에 대해서 간략히 설명해주세요"
    validations:
      required: false
  - type: textarea
    id: tasks
    attributes:
      label: "✅ TODO (Tasks)"
      description: "해당 이슈에 대해 필요한 작업목록을 작성해주세요"
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: "🔎 Reference"
      description: "추가 참고사항이 있다면 작성해주세요"
    validations:
      required: false
