name: 'Jira 연동 이슈 생성'
description: 'GitHub 이슈를 생성하면서 자동으로 Jira Task를 만듭니다.'
labels: ['order', 'jira']
title: '이슈 제목을 입력해주세요'
body:
  - type: input
    id: parentIssueKey
    attributes:
      label: '상위 Jira 티켓 번호'
      description: '상위 작업의 Jira 티켓 키를 입력하세요 (예: NUGUDI-123)'
      placeholder: 'NUGUDI-000'
    validations:
      required: true

  - type: input
    id: issueSummary
    attributes:
      label: '이슈 요약'
      description: '이슈의 간단한 제목을 입력하세요.'
      placeholder: '예: 주문 처리 로직 개선'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '작업 목록'
      description: '구체적인 작업 항목을 작성하세요.'
      value: |
        - [ ] Task 1
        - [ ] Task 2
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: '참고 자료'
      description: '관련된 스크린샷, 링크, 로그 등을 첨부하세요.'
    validations:
      required: false
