/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * 너구디 API
 * 구내식당 플랫폼 API
 * OpenAPI spec version: 1.0.0
 */
export interface SignUpSocialRequest {
  /** 닉네임 */
  nickname: string;
  /** 개인정보 처리방침 약관 동의 여부 */
  privacyPolicy: boolean;
  /** 이용약관 동의 여부 */
  termsOfService: boolean;
  /** 위치정보 수집·이용약관 동의 여부  */
  locationInfo: boolean;
  /** 마케팅 이메일 수신 동의 여부 (선택적, 기본값: false) */
  marketingEmail?: boolean;
  deviceInfo: UserDeviceInfoDTO;
}

/**
 * 디바이스 타입
 */
export type UserDeviceInfoDTODeviceType =
  | "IOS"
  | "ANDROID"
  | "WEB"
  | "IOS"
  | "ANDROID"
  | "WEB";
/**
 * 디바이스 정보 (일반/소셜 공통)
 */
export interface UserDeviceInfoDTO {
  /** 디바이스 타입 */
  deviceType: UserDeviceInfoDTODeviceType;
  /** 디바이스 고유 ID */
  deviceUniqueId: string;
  /** 디바이스 이름 */
  deviceName?: string;
  /** 디바이스 모델 */
  deviceModel?: string;
  /** OS 버전 */
  osVersion?: string;
  /** 앱 버전 */
  appVersion?: string;
  /** 푸시 토큰 (알림 동의시에만 필수) */
  pushToken?: string;
}

/**
 * 회원가입 성공 응답 (일반/소셜 공통)
 */
export interface SignUpResponse {
  /** 사용자 ID */
  userId?: number;
  /** 사용자 이메일 */
  email?: string;
  /** 사용자 닉네임 */
  nickname?: string;
  /** 액세스 토큰 */
  accessToken?: string;
  /** 리프레시 토큰 */
  refreshToken?: string;
  /** 액세스 토큰 만료 시간 */
  accessTokenExpiresAt?: Date;
  /** 리프레시 토큰 만료 시간 */
  refreshTokenExpiresAt?: Date;
}

export interface SuccessResponseSignUpResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: SignUpResponse;
}

/**
 * 일반 회원가입 요청 정보
 */
export interface SignUpLocalRequest {
  /** 닉네임 */
  nickname: string;
  /** 이메일 */
  email: string;
  /** 비밀번호 (최소 8자 이상, 최대 20자 이하, 영문/숫자/특수문자/대문자 1개 이상 포함) */
  password: string;
  /** 개인정보 처리방침 약관 동의 여부 */
  privacyPolicy: boolean;
  /** 이용약관 동의 여부 */
  termsOfService: boolean;
  /** 위치정보 수집·이용약관 동의 여부  */
  locationInfo: boolean;
  /** 마케팅 이메일 수신 동의 여부 (선택적, 기본값: false) */
  marketingEmail?: boolean;
  deviceInfo: UserDeviceInfoDTO;
}

/**
 * 토큰 갱신 응답
 */
export interface RefreshTokenResponse {
  /** 새로운 액세스 토큰 */
  accessToken?: string;
  /** 새로운 리프레시 토큰 */
  refreshToken?: string;
  /** 액세스 토큰 만료 시간 */
  accessTokenExpiresAt?: Date;
  /** 리프레시 토큰 만료 시간 */
  refreshTokenExpiresAt?: Date;
}

export interface SuccessResponseRefreshTokenResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: RefreshTokenResponse;
}

/**
 * 로그아웃 응답
 */
export interface LogoutResponse {
  /** 로그아웃 처리 시간 */
  logoutAt?: Date;
}

export interface SuccessResponseLogoutResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: LogoutResponse;
}

/**
 * 네이버 소셜 로그인 요청
 */
export interface NaverLoginRequest {
  /** 네이버 OAuth 인가 코드 (네이버 로그인 후 발급받은 authorization code) */
  code: string;
  /** 네이버 인증 시 사용한 redirect URI (인가 URL 조회 시 전달한 값과 동일해야 함) */
  redirectUri: string;
  /** CSRF 방지를 위한 상태 토큰 (선택적, 인가 URL 조회 시 사용한 값과 동일해야 함) */
  state?: string;
  deviceInfo: UserDeviceInfoDTO;
}

/**
 * 카카오 로그인 상태
 */
export type SocialLoginResponseStatus = "EXISTING_USER" | "NEW_USER";
/**
 * 소셜 로그인 응답
 */
export interface SocialLoginResponse {
  /** 카카오 로그인 상태 */
  status?: SocialLoginResponseStatus;
  /** 사용자 ID (기존 회원인 경우) */
  userId?: number;
  /** 사용자 닉네임 (기존 회원인 경우) */
  nickname?: string;
  /** 프로필 이미지 URL */
  profileImageUrl?: string;
  /** 액세스 토큰 (기존 회원인 경우) */
  accessToken?: string;
  /** 리프레시 토큰 (기존 회원인 경우) */
  refreshToken?: string;
  /** 액세스 토큰 만료 시간 */
  accessTokenExpiresAt?: Date;
  /** 리프레시 토큰 만료 시간 */
  refreshTokenExpiresAt?: Date;
  /** 등록 토큰 (신규 회원인 경우) */
  registrationToken?: string;
  /** 등록 토큰 만료 시간 (신규 회원인 경우) */
  registrationTokenExpiresAt?: Date;
}

export interface SuccessResponseSocialLoginResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: SocialLoginResponse;
}

/**
 * 일반 로그인 요청
 */
export interface LocalLoginRequest {
  /** 이메일 */
  email: string;
  /** 비밀번호 */
  password: string;
  deviceInfo: UserDeviceInfoDTO;
}

/**
 * 일반 로그인 응답
 */
export interface LocalLoginResponse {
  /** 사용자 ID */
  userId?: number;
  /** 사용자 이메일 */
  email?: string;
  /** 사용자 닉네임 */
  nickname?: string;
  /** 프로필 이미지 URL */
  profileImageUrl?: string;
  /** 액세스 토큰 */
  accessToken?: string;
  /** 리프레시 토큰 */
  refreshToken?: string;
  /** 액세스 토큰 만료 시간 */
  accessTokenExpiresAt?: Date;
  /** 리프레시 토큰 만료 시간 */
  refreshTokenExpiresAt?: Date;
}

export interface SuccessResponseLocalLoginResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: LocalLoginResponse;
}

/**
 * 카카오 소셜 로그인 요청
 */
export interface KakaoLoginRequest {
  /** 카카오 OAuth 인가 코드 (카카오 로그인 후 발급받은 authorization code) */
  code: string;
  /** 카카오 인증 시 사용한 redirect URI (인가 URL 조회 시 전달한 값과 동일해야 함) */
  redirectUri: string;
  deviceInfo: UserDeviceInfoDTO;
}

/**
 * 구글 소셜 로그인 요청
 */
export interface GoogleLoginRequest {
  /** 구글 OAuth 인가 코드 (구글 로그인 후 발급받은 authorization code) */
  code: string;
  /** 구글 인증 시 사용한 redirect URI (인가 URL 조회 시 전달한 값과 동일해야 함) */
  redirectUri: string;
  deviceInfo: UserDeviceInfoDTO;
}

/**
 * 인증 목적 (SIGNUP: 회원가입, PASSWORD_RESET: 비밀번호 재설정)
 */
export type EmailVerifyRequestPurpose = "SIGNUP" | "PASSWORD_RESET";
/**
 * 이메일 인증 코드 확인 요청
 */
export interface EmailVerifyRequest {
  /** 이메일 */
  email: string;
  /** 인증 코드 */
  code: string;
  /** 인증 목적 (SIGNUP: 회원가입, PASSWORD_RESET: 비밀번호 재설정) */
  purpose: EmailVerifyRequestPurpose;
}

/**
 * 이메일 인증 코드 확인 응답
 */
export interface EmailVerifyResponse {
  /** 인증 성공 여부 */
  verified?: boolean;
}

export interface SuccessResponseEmailVerifyResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: EmailVerifyResponse;
}

/**
 * 인증 목적 (SIGNUP: 회원가입, PASSWORD_RESET: 비밀번호 재설정)
 */
export type EmailVerificationRequestPurpose = "SIGNUP" | "PASSWORD_RESET";
/**
 * 이메일 인증 코드 발송 요청
 */
export interface EmailVerificationRequest {
  /** 이메일 */
  email: string;
  /** 인증 목적 (SIGNUP: 회원가입, PASSWORD_RESET: 비밀번호 재설정) */
  purpose: EmailVerificationRequestPurpose;
}

/**
 * 이메일 인증 코드 발송 응답
 */
export interface EmailVerificationResponse {
  /** 만료 시간(초) */
  expiresInSeconds?: number;
}

export interface SuccessResponseEmailVerificationResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: EmailVerificationResponse;
}

/**
 * 영업 요일 (예: 평일만 영업하는 경우)
 */
export type BusinessHoursRequestOperatingDaysItem =
  | "MONDAY"
  | "TUESDAY"
  | "WEDNESDAY"
  | "THURSDAY"
  | "FRIDAY"
  | "SATURDAY"
  | "SUNDAY";
/**
 * 구내식당 영업시간 정보
 */
export interface BusinessHoursRequest {
  lunchStartTime?: LocalTime;
  lunchEndTime?: LocalTime;
  dinnerStartTime?: LocalTime;
  dinnerEndTime?: LocalTime;
  /** 영업 요일 (예: 평일만 영업하는 경우) */
  operatingDays: BusinessHoursRequestOperatingDaysItem[];
  /** 특별 휴무일 (공휴일 등) */
  specialHolidays?: Date[];
  /** 영업시간 비고 */
  note?: string;
}

/**
 * 저녁 종료 시간
 */
export interface LocalTime {
  hour?: number;
  minute?: number;
  second?: number;
  nano?: number;
}

export interface RegisterCafeteriaRequest {
  name: string;
  address: string;
  addressDetail: string;
  latitude?: number;
  longitude?: number;
  phone?: string;
  description?: string;
  oneLineIntro?: string;
  mealTicketPrice?: number;
  mainImageFileId?: number;
  businessHours?: BusinessHoursRequest;
  takeoutAvailable: boolean;
}

export interface RegisterCafeteriaResponse {
  cafeteriaId?: number;
  name?: string;
  address?: string;
  addressDetail?: string;
  latitude?: number;
  longitude?: number;
  phone?: string;
  description?: string;
  oneLineIntro?: string;
  mealTicketPrice?: number;
  mainImageFileId?: number;
  takeoutAvailable?: boolean;
  createdAt?: Date;
}

export interface SuccessResponseRegisterCafeteriaResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: RegisterCafeteriaResponse;
}

export type MenuItemDtoCategory =
  | "RICE"
  | "SOUP"
  | "MAIN_DISH"
  | "SIDE_DISH"
  | "KIMCHI"
  | "SALAD"
  | "DESSERT"
  | "DRINK"
  | "SPECIAL";
/**
 * 메뉴 항목 목록
 */
export interface MenuItemDto {
  name?: string;
  category?: MenuItemDtoCategory;
  calories?: number;
  caloriesSource?: string;
  displayOrder?: number;
}

/**
 * 식사 시간대 (BREAKFAST, LUNCH, DINNER)
 */
export type RegisterCafeteriaMenuRequestMealType =
  | "BREAKFAST"
  | "LUNCH"
  | "DINNER";
/**
 * 구내식당 식단표 등록 요청
 */
export interface RegisterCafeteriaMenuRequest {
  /** 구내식당 ID */
  restaurantId: number;
  /** 식단 날짜 */
  menuDate: Date;
  /** 식사 시간대 (BREAKFAST, LUNCH, DINNER) */
  mealType: RegisterCafeteriaMenuRequestMealType;
  /** 메뉴 항목 목록 */
  menuItems: MenuItemDto[];
  /** 메뉴 이미지 파일 ID */
  menuImageFileId?: number;
  /** 특이사항 (예: 알레르기 정보, 추가 안내사항) */
  specialNote?: string;
}

/**
 * 식사 시간대
 */
export type RegisterCafeteriaMenuResponseMealType =
  | "BREAKFAST"
  | "LUNCH"
  | "DINNER";
/**
 * 구내식당 식단표 등록 응답
 */
export interface RegisterCafeteriaMenuResponse {
  /** 식단표 ID */
  menuId?: number;
  /** 구내식당 ID */
  restaurantId?: number;
  /** 식단 날짜 */
  menuDate?: Date;
  /** 식사 시간대 */
  mealType?: RegisterCafeteriaMenuResponseMealType;
  /** 메뉴 항목 목록 */
  menuItems?: MenuItemDto[];
  /** 총 칼로리 */
  totalCalories?: number;
  /** 메뉴 이미지 파일 ID */
  menuImageFileId?: number;
  /** 특이사항 */
  specialNote?: string;
  /** 등록 일시 */
  createdAt?: Date;
}

export interface SuccessResponseRegisterCafeteriaMenuResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: RegisterCafeteriaMenuResponse;
}

/**
 * 닉네임 사용 가능 여부 확인 응답
 */
export interface NicknameCheckResponse {
  /** 확인한 닉네임 */
  nickname?: string;
  /** 사용 가능한지 여부 */
  available?: boolean;
}

export interface SuccessResponseNicknameCheckResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: NicknameCheckResponse;
}

export interface GetMyProfileResponse {
  profile?: UserProfileDTO;
  account?: UserAccountDTO;
  health?: HealthInfoDTO;
}

export interface HealthInfoDTO {
  height?: number;
  weight?: number;
}

export interface SuccessResponseGetMyProfileResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: GetMyProfileResponse;
}

export type UserAccountDTOProvider =
  | "LOCAL"
  | "GOOGLE"
  | "APPLE"
  | "KAKAO"
  | "NAVER";
export interface UserAccountDTO {
  provider?: UserAccountDTOProvider;
  email?: string;
}

export interface UserProfileDTO {
  userId?: number;
  nickname?: string;
  profileImageUrl?: string;
  joinDate?: Date;
}

export interface BusinessHoursDTO {
  lunch?: TimeRangeDTO;
  dinner?: TimeRangeDTO;
  note?: string;
}

export interface CafeteriaInfoDTO {
  id?: number;
  name?: string;
  address?: string;
  addressDetail?: string;
  latitude?: number;
  longitude?: number;
  phone?: string;
  mealTicketPrice?: number;
  takeoutAvailable?: boolean;
  businessHours?: BusinessHoursDTO;
}

export interface GetCafeteriaWithMenuResponse {
  cafeteria?: CafeteriaInfoDTO;
  menus?: MenuInfoDTO[];
}

export interface MenuInfoDTO {
  mealType?: string;
  menuItems?: MenuItemDto[];
  specialNote?: string;
  nutritionInfo?: NutritionInfoDTO;
}

export interface NutritionInfoDTO {
  totalCalories?: number;
  dailyPercentage?: number;
  walkingSteps?: number;
  runningKm?: number;
  cyclingKm?: number;
  stairsFloors?: number;
}

export interface PageInfo {
  nextCursor?: number;
  size?: number;
  hasNext?: boolean;
}

export interface PageResponseGetCafeteriaWithMenuResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: GetCafeteriaWithMenuResponse[];
  pageInfo?: PageInfo;
}

export interface TimeRangeDTO {
  start?: LocalTime;
  end?: LocalTime;
}

export interface GetCafeteriaResponse {
  cafeteria?: CafeteriaInfoDTO;
}

export interface SuccessResponseGetCafeteriaResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: GetCafeteriaResponse;
}

export interface GetCafeteriaMenuResponse {
  menuDate?: Date;
  menus?: MenuInfoDTO[];
}

export interface SuccessResponseGetCafeteriaMenuResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: GetCafeteriaMenuResponse;
}

export interface GetCafeteriaMenuAvailabilityResponse {
  year?: number;
  month?: number;
  daysWithMenu?: number[];
}

export interface SuccessResponseGetCafeteriaMenuAvailabilityResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: GetCafeteriaMenuAvailabilityResponse;
}

export interface GetNaverAuthorizeResponse {
  authorizeUrl?: string;
}

export interface SuccessResponseGetNaverAuthorizeResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: GetNaverAuthorizeResponse;
}

export interface GetKakaoAuthorizeResponse {
  authorizeUrl?: string;
}

export interface SuccessResponseGetKakaoAuthorizeResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: GetKakaoAuthorizeResponse;
}

export interface GetGoogleAuthorizeResponse {
  authorizeUrl?: string;
}

export interface SuccessResponseGetGoogleAuthorizeResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: GetGoogleAuthorizeResponse;
}

export type SendEmailVerificationCode200 = {
  message?: string;
};

export type CheckNicknameAvailabilityParams = {
  /**
   * 확인할 닉네임 (2~12자, 한글/영문/숫자만)
   */
  nickname: string;
};

export type GetCafeteriasWithMenuParams = {
  /**
   * 커서 (이전 페이지의 마지막 구내식당 ID, 첫 페이지는 null)
   */
  cursor?: number;
  /**
   * 조회할 개수 (기본 10개)
   */
  size?: number;
  /**
   * 조회할 식단표 날짜 (null이면 오늘)
   */
  date?: Date;
};

export type GetCafeteriaMenuByDateParams = {
  /**
   * 조회할 식단표 날짜 (null이면 오늘)
   */
  date?: Date;
};

export type GetCafeteriaMenuAvailabilityParams = {
  /**
   * 조회할 년도 (2025 이상)
   * @minimum 2025
   */
  year: number;
  /**
   * 조회할 월 (1-12)
   * @minimum 1
   * @maximum 12
   */
  month: number;
};

export type GetNaverAuthorizeUrlParams = {
  /**
   * 네이버 인증 완료 후 리다이렉트될 URI
   */
  redirectUri: string;
  /**
   * CSRF 방지를 위한 상태 토큰 (선택)
   */
  state?: string;
};

export type GetKakaoAuthorizeUrlParams = {
  /**
   * 카카오 인증 완료 후 리다이렉트될 URI
   */
  redirectUri: string;
};

export type GetGoogleAuthorizeUrlParams = {
  /**
   * 구글 인증 완료 후 리다이렉트될 URI
   */
  redirectUri: string;
};
