/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 너구디 API
 * 구내식당 플랫폼 API
 * OpenAPI spec version: v1
 */
/**
 * 디바이스 타입
 */
export type DeviceInfoDtoDeviceType =
  | "IOS"
  | "ANDROID"
  | "WEB"
  | "IOS"
  | "ANDROID"
  | "WEB";
/**
 * 디바이스 정보 (일반/소셜 공통)
 */
export interface DeviceInfoDto {
  /** 디바이스 타입 */
  deviceType: DeviceInfoDtoDeviceType;
  /** 디바이스 고유 ID */
  deviceUniqueId?: string;
  /** 디바이스 이름 */
  deviceName?: string;
  /** 디바이스 모델 */
  deviceModel?: string;
  /** OS 버전 */
  osVersion?: string;
  /** 앱 버전 */
  appVersion?: string;
  /** 푸시 토큰 (알림 동의시에만 필수) */
  pushToken?: string;
}

/**
 * 일반 회원가입 요청 정보
 */
export interface SignUpLocalRequest {
  /** 닉네임 */
  nickname: string;
  /** 이메일 */
  email: string;
  /** 비밀번호 (최소 8자 이상, 최대 20자 이하, 영문/숫자/특수문자/대문자 1개 이상 포함) */
  password: string;
  /** 약관 동의 목록 */
  termAgreements: TermAgreementDto[];
  /** 알림 수신 동의 여부 */
  acceptsNotifications: boolean;
  /** 마케팅 이메일 수신 동의 여부 */
  acceptsMarketingEmail: boolean;
  deviceInfo: DeviceInfoDto;
}

/**
 * 약관 동의 정보 (일반/소셜 공통)
 */
export interface TermAgreementDto {
  /** 약관 정책 ID */
  termPolicyId: number;
  /** 동의 여부 */
  isAgreed: boolean;
}

/**
 * 회원가입 성공 응답 (일반/소셜 공통)
 */
export interface SignUpResponse {
  /** 사용자 ID */
  userId?: number;
  /** 성공 메시지 */
  message?: string;
}

export interface SuccessResponseSignUpResponse {
  timestamp?: Date;
  success?: boolean;
  message?: string;
  data?: SignUpResponse;
}

/**
 * 인증 목적 (SIGNUP: 회원가입, PASSWORD_RESET: 비밀번호 재설정)
 */
export type EmailVerifyRequestPurpose = "SIGNUP" | "PASSWORD_RESET";
/**
 * 이메일 인증 코드 확인 요청
 */
export interface EmailVerifyRequest {
  /** 이메일 */
  email: string;
  /** 인증 코드 */
  code: string;
  /** 인증 목적 (SIGNUP: 회원가입, PASSWORD_RESET: 비밀번호 재설정) */
  purpose: EmailVerifyRequestPurpose;
}

/**
 * 이메일 인증 코드 확인 응답
 */
export interface EmailVerifyResponse {
  /** 인증 성공 여부 */
  verified?: boolean;
  /** 성공 메시지 */
  message?: string;
}

export interface SuccessResponseEmailVerifyResponse {
  timestamp?: Date;
  success?: boolean;
  message?: string;
  data?: EmailVerifyResponse;
}

/**
 * 인증 목적 (SIGNUP: 회원가입, PASSWORD_RESET: 비밀번호 재설정)
 */
export type EmailVerificationRequestPurpose = "SIGNUP" | "PASSWORD_RESET";
/**
 * 이메일 인증 코드 발송 요청
 */
export interface EmailVerificationRequest {
  /** 이메일 */
  email: string;
  /** 인증 목적 (SIGNUP: 회원가입, PASSWORD_RESET: 비밀번호 재설정) */
  purpose: EmailVerificationRequestPurpose;
}

/**
 * 이메일 인증 코드 발송 응답
 */
export interface EmailVerificationResponse {
  /** 성공 메시지 */
  message?: string;
  /** 만료 시간(초) */
  expiresInSeconds?: number;
}

export interface SuccessResponseEmailVerificationResponse {
  timestamp?: Date;
  success?: boolean;
  message?: string;
  data?: EmailVerificationResponse;
}

export type SendEmailVerificationCode200 = {
  message?: string;
};
