/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 너구디 API
 * 구내식당 플랫폼 API
 * OpenAPI spec version: v1
 */
import { faker } from "@faker-js/faker";

import { delay, HttpResponse, http } from "msw";

import type {
  SendEmailVerificationCode200,
  SuccessResponseEmailVerifyResponse,
  SuccessResponseLocalLoginResponse,
  SuccessResponseNicknameCheckResponse,
  SuccessResponseRefreshTokenResponse,
  SuccessResponseSignUpResponse,
} from "./index.schemas";

export const getSignUpLocalResponseMock = (
  overrideResponse: Partial<SuccessResponseSignUpResponse> = {},
): SuccessResponseSignUpResponse => ({
  timestamp: faker.helpers.arrayElement([
    new Date(`${faker.date.past().toISOString().split(".")[0]}Z`),
    undefined,
  ]),
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  data: faker.helpers.arrayElement([
    {
      userId: faker.helpers.arrayElement([
        faker.number.int({
          min: undefined,
          max: undefined,
          multipleOf: undefined,
        }),
        undefined,
      ]),
      email: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      nickname: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      accessToken: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      refreshToken: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      accessTokenExpiresAt: faker.helpers.arrayElement([
        new Date(`${faker.date.past().toISOString().split(".")[0]}Z`),
        undefined,
      ]),
      refreshTokenExpiresAt: faker.helpers.arrayElement([
        new Date(`${faker.date.past().toISOString().split(".")[0]}Z`),
        undefined,
      ]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getRefreshTokenResponseMock = (
  overrideResponse: Partial<SuccessResponseRefreshTokenResponse> = {},
): SuccessResponseRefreshTokenResponse => ({
  timestamp: faker.helpers.arrayElement([
    new Date(`${faker.date.past().toISOString().split(".")[0]}Z`),
    undefined,
  ]),
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  data: faker.helpers.arrayElement([
    {
      accessToken: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      refreshToken: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      accessTokenExpiresAt: faker.helpers.arrayElement([
        new Date(`${faker.date.past().toISOString().split(".")[0]}Z`),
        undefined,
      ]),
      refreshTokenExpiresAt: faker.helpers.arrayElement([
        new Date(`${faker.date.past().toISOString().split(".")[0]}Z`),
        undefined,
      ]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getLocalLoginResponseMock = (
  overrideResponse: Partial<SuccessResponseLocalLoginResponse> = {},
): SuccessResponseLocalLoginResponse => ({
  timestamp: faker.helpers.arrayElement([
    new Date(`${faker.date.past().toISOString().split(".")[0]}Z`),
    undefined,
  ]),
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  data: faker.helpers.arrayElement([
    {
      userId: faker.helpers.arrayElement([
        faker.number.int({
          min: undefined,
          max: undefined,
          multipleOf: undefined,
        }),
        undefined,
      ]),
      email: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      nickname: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      profileImageUrl: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      accessToken: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      refreshToken: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      accessTokenExpiresAt: faker.helpers.arrayElement([
        new Date(`${faker.date.past().toISOString().split(".")[0]}Z`),
        undefined,
      ]),
      refreshTokenExpiresAt: faker.helpers.arrayElement([
        new Date(`${faker.date.past().toISOString().split(".")[0]}Z`),
        undefined,
      ]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getVerifyEmailCodeResponseMock = (
  overrideResponse: Partial<SuccessResponseEmailVerifyResponse> = {},
): SuccessResponseEmailVerifyResponse => ({
  timestamp: faker.helpers.arrayElement([
    new Date(`${faker.date.past().toISOString().split(".")[0]}Z`),
    undefined,
  ]),
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  data: faker.helpers.arrayElement([
    {
      verified: faker.helpers.arrayElement([
        faker.datatype.boolean(),
        undefined,
      ]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getSendEmailVerificationCodeResponseMock = (
  overrideResponse: Partial<SendEmailVerificationCode200> = {},
): SendEmailVerificationCode200 => ({
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getCheckNicknameAvailabilityResponseMock = (
  overrideResponse: Partial<SuccessResponseNicknameCheckResponse> = {},
): SuccessResponseNicknameCheckResponse => ({
  timestamp: faker.helpers.arrayElement([
    new Date(`${faker.date.past().toISOString().split(".")[0]}Z`),
    undefined,
  ]),
  success: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  data: faker.helpers.arrayElement([
    {
      nickname: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      available: faker.helpers.arrayElement([
        faker.datatype.boolean(),
        undefined,
      ]),
    },
    undefined,
  ]),
  ...overrideResponse,
});

export const getSignUpLocalMockHandler = (
  overrideResponse?:
    | SuccessResponseSignUpResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) =>
        | Promise<SuccessResponseSignUpResponse>
        | SuccessResponseSignUpResponse),
) => {
  return http.post("*/api/v1/auth/signup/local", async (info) => {
    await delay(500);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getSignUpLocalResponseMock(),
      ),
      { status: 201, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getRefreshTokenMockHandler = (
  overrideResponse?:
    | SuccessResponseRefreshTokenResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) =>
        | Promise<SuccessResponseRefreshTokenResponse>
        | SuccessResponseRefreshTokenResponse),
) => {
  return http.post("*/api/v1/auth/refresh", async (info) => {
    await delay(500);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getRefreshTokenResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getLocalLoginMockHandler = (
  overrideResponse?:
    | SuccessResponseLocalLoginResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) =>
        | Promise<SuccessResponseLocalLoginResponse>
        | SuccessResponseLocalLoginResponse),
) => {
  return http.post("*/api/v1/auth/login/local", async (info) => {
    await delay(500);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getLocalLoginResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getVerifyEmailCodeMockHandler = (
  overrideResponse?:
    | SuccessResponseEmailVerifyResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) =>
        | Promise<SuccessResponseEmailVerifyResponse>
        | SuccessResponseEmailVerifyResponse),
) => {
  return http.post("*/api/v1/auth/email/verify-code", async (info) => {
    await delay(500);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getVerifyEmailCodeResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getSendEmailVerificationCodeMockHandler = (
  overrideResponse?:
    | SendEmailVerificationCode200
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) =>
        | Promise<SendEmailVerificationCode200>
        | SendEmailVerificationCode200),
) => {
  return http.post("*/api/v1/auth/email/send-code", async (info) => {
    await delay(500);

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getSendEmailVerificationCodeResponseMock(),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  });
};

export const getCheckNicknameAvailabilityMockHandler = (
  overrideResponse?:
    | SuccessResponseNicknameCheckResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<SuccessResponseNicknameCheckResponse>
        | SuccessResponseNicknameCheckResponse),
) => {
  return http.get(
    "*/api/v1/users/nicknames/:nickname/availability",
    async (info) => {
      await delay(500);

      return new HttpResponse(
        JSON.stringify(
          overrideResponse !== undefined
            ? typeof overrideResponse === "function"
              ? await overrideResponse(info)
              : overrideResponse
            : getCheckNicknameAvailabilityResponseMock(),
        ),
        { status: 200, headers: { "Content-Type": "application/json" } },
      );
    },
  );
};
export const getApiMock = () => [
  getSignUpLocalMockHandler(),
  getRefreshTokenMockHandler(),
  getLocalLoginMockHandler(),
  getVerifyEmailCodeMockHandler(),
  getSendEmailVerificationCodeMockHandler(),
  getCheckNicknameAvailabilityMockHandler(),
];
