/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 너구디 API
 * 구내식당 플랫폼 API
 * OpenAPI spec version: 1.0.0
 */
export interface SignUpSocialRequest {
  /** 닉네임 */
  nickname: string;
  /** 개인정보 처리방침 약관 동의 여부 */
  privacyPolicy: boolean;
  /** 이용약관 동의 여부 */
  termsOfService: boolean;
  /** 위치정보 수집·이용약관 동의 여부  */
  locationInfo: boolean;
  /** 마케팅 이메일 수신 동의 여부 (선택적, 기본값: false) */
  marketingEmail?: boolean;
  deviceInfo: UserDeviceInfoDTO;
}

/**
 * 디바이스 타입
 */
export type UserDeviceInfoDTODeviceType =
  | "IOS"
  | "ANDROID"
  | "WEB"
  | "IOS"
  | "ANDROID"
  | "WEB";
/**
 * 디바이스 정보 (일반/소셜 공통)
 */
export interface UserDeviceInfoDTO {
  /** 디바이스 타입 */
  deviceType: UserDeviceInfoDTODeviceType;
  /** 디바이스 고유 ID */
  deviceUniqueId: string;
  /** 디바이스 이름 */
  deviceName?: string;
  /** 디바이스 모델 */
  deviceModel?: string;
  /** OS 버전 */
  osVersion?: string;
  /** 앱 버전 */
  appVersion?: string;
  /** 푸시 토큰 (알림 동의시에만 필수) */
  pushToken?: string;
}

/**
 * 회원가입 성공 응답 (일반/소셜 공통)
 */
export interface SignUpResponse {
  /** 사용자 ID */
  userId?: number;
  /** 사용자 이메일 */
  email?: string;
  /** 사용자 닉네임 */
  nickname?: string;
  /** 액세스 토큰 */
  accessToken?: string;
  /** 리프레시 토큰 */
  refreshToken?: string;
  /** 액세스 토큰 만료 시간 */
  accessTokenExpiresAt?: Date;
  /** 리프레시 토큰 만료 시간 */
  refreshTokenExpiresAt?: Date;
}

export interface SuccessResponseSignUpResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: SignUpResponse;
}

/**
 * 일반 회원가입 요청 정보
 */
export interface SignUpLocalRequest {
  /** 닉네임 */
  nickname: string;
  /** 이메일 */
  email: string;
  /** 비밀번호 (최소 8자 이상, 최대 20자 이하, 영문/숫자/특수문자/대문자 1개 이상 포함) */
  password: string;
  /** 개인정보 처리방침 약관 동의 여부 */
  privacyPolicy: boolean;
  /** 이용약관 동의 여부 */
  termsOfService: boolean;
  /** 위치정보 수집·이용약관 동의 여부  */
  locationInfo: boolean;
  /** 마케팅 이메일 수신 동의 여부 (선택적, 기본값: false) */
  marketingEmail?: boolean;
  deviceInfo: UserDeviceInfoDTO;
}

/**
 * 토큰 갱신 응답
 */
export interface RefreshTokenResponse {
  /** 새로운 액세스 토큰 */
  accessToken?: string;
  /** 새로운 리프레시 토큰 */
  refreshToken?: string;
  /** 액세스 토큰 만료 시간 */
  accessTokenExpiresAt?: Date;
  /** 리프레시 토큰 만료 시간 */
  refreshTokenExpiresAt?: Date;
}

export interface SuccessResponseRefreshTokenResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: RefreshTokenResponse;
}

/**
 * 로그아웃 응답
 */
export interface LogoutResponse {
  /** 로그아웃 처리 시간 */
  logoutAt?: Date;
}

export interface SuccessResponseLogoutResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: LogoutResponse;
}

/**
 * 일반 로그인 요청
 */
export interface LocalLoginRequest {
  /** 이메일 */
  email: string;
  /** 비밀번호 */
  password: string;
  deviceInfo: UserDeviceInfoDTO;
}

/**
 * 일반 로그인 응답
 */
export interface LocalLoginResponse {
  /** 사용자 ID */
  userId?: number;
  /** 사용자 이메일 */
  email?: string;
  /** 사용자 닉네임 */
  nickname?: string;
  /** 프로필 이미지 URL */
  profileImageUrl?: string;
  /** 액세스 토큰 */
  accessToken?: string;
  /** 리프레시 토큰 */
  refreshToken?: string;
  /** 액세스 토큰 만료 시간 */
  accessTokenExpiresAt?: Date;
  /** 리프레시 토큰 만료 시간 */
  refreshTokenExpiresAt?: Date;
}

export interface SuccessResponseLocalLoginResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: LocalLoginResponse;
}

/**
 * 카카오 소셜 로그인 요청
 */
export interface KakaoLoginRequest {
  /** 카카오 OAuth 인가 코드 (카카오 로그인 후 발급받은 authorization code) */
  code: string;
  deviceInfo: UserDeviceInfoDTO;
}

/**
 * 카카오 로그인 상태
 */
export type KakaoLoginResponseStatus = "EXISTING_USER" | "NEW_USER";
/**
 * 카카오 로그인 응답
 */
export interface KakaoLoginResponse {
  /** 카카오 로그인 상태 */
  status?: KakaoLoginResponseStatus;
  /** 사용자 ID (기존 회원인 경우) */
  userId?: number;
  /** 사용자 닉네임 (기존 회원인 경우) */
  nickname?: string;
  /** 프로필 이미지 URL */
  profileImageUrl?: string;
  /** 액세스 토큰 (기존 회원인 경우) */
  accessToken?: string;
  /** 리프레시 토큰 (기존 회원인 경우) */
  refreshToken?: string;
  /** 액세스 토큰 만료 시간 */
  accessTokenExpiresAt?: Date;
  /** 리프레시 토큰 만료 시간 */
  refreshTokenExpiresAt?: Date;
  /** 등록 토큰 (신규 회원인 경우) */
  registrationToken?: string;
  /** 등록 토큰 만료 시간 (신규 회원인 경우) */
  registrationTokenExpiresAt?: Date;
}

export interface SuccessResponseKakaoLoginResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: KakaoLoginResponse;
}

/**
 * 인증 목적 (SIGNUP: 회원가입, PASSWORD_RESET: 비밀번호 재설정)
 */
export type EmailVerifyRequestPurpose = "SIGNUP" | "PASSWORD_RESET";
/**
 * 이메일 인증 코드 확인 요청
 */
export interface EmailVerifyRequest {
  /** 이메일 */
  email: string;
  /** 인증 코드 */
  code: string;
  /** 인증 목적 (SIGNUP: 회원가입, PASSWORD_RESET: 비밀번호 재설정) */
  purpose: EmailVerifyRequestPurpose;
}

/**
 * 이메일 인증 코드 확인 응답
 */
export interface EmailVerifyResponse {
  /** 인증 성공 여부 */
  verified?: boolean;
}

export interface SuccessResponseEmailVerifyResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: EmailVerifyResponse;
}

/**
 * 인증 목적 (SIGNUP: 회원가입, PASSWORD_RESET: 비밀번호 재설정)
 */
export type EmailVerificationRequestPurpose = "SIGNUP" | "PASSWORD_RESET";
/**
 * 이메일 인증 코드 발송 요청
 */
export interface EmailVerificationRequest {
  /** 이메일 */
  email: string;
  /** 인증 목적 (SIGNUP: 회원가입, PASSWORD_RESET: 비밀번호 재설정) */
  purpose: EmailVerificationRequestPurpose;
}

/**
 * 이메일 인증 코드 발송 응답
 */
export interface EmailVerificationResponse {
  /** 만료 시간(초) */
  expiresInSeconds?: number;
}

export interface SuccessResponseEmailVerificationResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: EmailVerificationResponse;
}

/**
 * 닉네임 사용 가능 여부 확인 응답
 */
export interface NicknameCheckResponse {
  /** 확인한 닉네임 */
  nickname?: string;
  /** 사용 가능한지 여부 */
  available?: boolean;
}

export interface SuccessResponseNicknameCheckResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: NicknameCheckResponse;
}

export interface GetMyProfileResponse {
  profile?: UserProfileDTO;
  account?: UserAccountDTO;
  health?: HealthInfoDTO;
}

export interface HealthInfoDTO {
  height?: number;
  weight?: number;
}

export interface SuccessResponseGetMyProfileResponse {
  timestamp?: Date;
  success?: boolean;
  code?: number;
  message?: string;
  data?: GetMyProfileResponse;
}

export type UserAccountDTOProvider =
  | "LOCAL"
  | "GOOGLE"
  | "APPLE"
  | "KAKAO"
  | "NAVER";
export interface UserAccountDTO {
  provider?: UserAccountDTOProvider;
  email?: string;
}

export interface UserProfileDTO {
  userId?: number;
  nickname?: string;
  profileImageUrl?: string;
  joinDate?: Date;
}

export type SendEmailVerificationCode200 = {
  message?: string;
};

export type CheckNicknameAvailabilityParams = {
  /**
   * 확인할 닉네임 (2~12자, 한글/영문/숫자만)
   */
  nickname: string;
};
