import { vars } from "@nugudi/themes";
import clsx from "clsx";
import React from "react";
import { BaseStyle, StyleSprinkles } from "@/core/style.css";
import type { FlexProps as HStackProps } from "@/layout/types";

const HStack = (props: HStackProps, ref: React.Ref<HTMLElement>) => {
  const {
    as = "div",
    color,
    background,
    align,
    basis,
    grow,
    justify,
    shrink,
    wrap,
    gap,
    // Width and height properties with shorthands
    width,
    w,
    height,
    h,
    maxWidth,
    maxW,
    minWidth,
    minW,
    maxHeight,
    maxH,
    minHeight,
    minH,
    size,
    maxSize,
    minSize,
    sizeX,
    sizeY,
    // Margin and padding properties with shorthands
    m,
    margin,
    marginTop,
    marginRight,
    marginBottom,
    marginLeft,
    mt,
    mr,
    mb,
    ml,
    mX,
    mY,
    p,
    padding,
    paddingTop,
    paddingRight,
    paddingBottom,
    paddingLeft,
    pt,
    pr,
    pb,
    pl,
    pX,
    pY,
    // Other style properties
    borderRadius,
    boxShadow,
    children,
    className,
    style,
    ...restProps
  } = props;

  const sprinkleProps = {
    // Width and height properties
    width,
    w,
    height,
    h,
    maxWidth,
    maxW,
    minWidth,
    minW,
    maxHeight,
    maxH,
    minHeight,
    minH,
    size,
    maxSize,
    minSize,
    sizeX,
    sizeY,
    // Margin and padding properties
    m,
    margin,
    marginTop,
    marginRight,
    marginBottom,
    marginLeft,
    mt,
    mr,
    mb,
    ml,
    mX,
    mY,
    p,
    padding,
    paddingTop,
    paddingRight,
    paddingBottom,
    paddingLeft,
    pt,
    pr,
    pb,
    pl,
    pX,
    pY,
    // Other style properties
    borderRadius,
    boxShadow,
  };

  return React.createElement(
    as,
    {
      ...restProps,
      ref,
      className: clsx([BaseStyle, StyleSprinkles(sprinkleProps), className]),
      style: {
        display: "flex",
        alignItems: align,
        justifyContent: justify,
        flexDirection: "row",
        flexWrap: wrap,
        flexGrow: grow,
        flexShrink: shrink,
        flexBasis: basis,
        gap,
        color: color && vars.colors.$scale?.[color]?.[700],
        background: background && vars.colors.$scale?.[background]?.[100],
        ...style,
      },
    },
    children,
  );
};

const _HStack = React.forwardRef(HStack);
export { _HStack as HStack };
