on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  transition:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        with:
          script: |
            const pr = context.payload.pull_request;
            const ticket = pr.title.match(/NUGUDI-\d+/)?.[0];
            if (!ticket) return;
